# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
 branches:
   include:
     - release/functions*

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'



steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

  
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: 'MelbourneModenApps.Functions/MelbourneModenApps.Functions.csproj'
    arguments: '--configuration $(buildConfiguration)'
- task: AzureFunctionApp@1
  inputs:
    azureSubscription: 'Pay-As-You-Go (951a84dd-fbb0-4ba0-bc31-4865ee7f4df3)'
    appType: 'functionApp'
    appName: 'melbournemeetup'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    deploymentMethod: 'auto'